In [2]:
import os

import pandas as pd
import numpy as np

In [5]:
data_path = "/work/frink/shaib.c/pattern_distillation/original_data"

In [10]:
cochrane = pd.read_csv(os.path.join(data_path, 'cochrane_train_inputs.csv'), index_col=0)

rotten_tomatoes_movies = pd.read_csv(os.path.join(data_path, 'rotten_tomatoes_movies.csv'))
rotten_tomatoes_critics = pd.read_csv(os.path.join(data_path, 'rotten_tomatoes_critic_reviews.csv'))

In [11]:
cochrane.head()

,ReviewID,PMID,Title,Abstract
0,CD007697,16394043,Aggressive surgical effort and improved surviv...,Residual disease after initial surgery for ova...
1,CD000174,8627434,Prophylactic indomethacin therapy in the first...,To determine whether a course of low-dose indo...
2,CD000174,2677294,Indomethacin reduces the risks of severe intra...,"A prospective, random selection, double-blind ..."
3,CD000174,3373404,Administration of indomethacin for the prevent...,One hundred twenty-two preterm infants were en...
4,CD000174,3321891,Early intravenous indomethacin prolongs respir...,Infants weighing 1500 g at birth requiring eit...

In [13]:
rotten_tomatoes_critics.head()

,rotten_tomatoes_link,critic_name,top_critic,publisher_name,review_type,review_score,review_date,review_content
0,m/0814255,Andrew L. Urban,False,Urban Cinefile,Fresh,NaN,2010-02-06,A fantasy adventure that fuses Greek mythology...
1,m/0814255,Louise Keller,False,Urban Cinefile,Fresh,NaN,2010-02-06,"Uma Thurman as Medusa, the gorgon with a coiff..."
2,m/0814255,NaN,False,FILMINK (Australia),Fresh,NaN,2010-02-09,With a top-notch cast and dazzling special eff...
3,m/0814255,Ben McEachen,False,Sunday Mail (Australia),Fresh,3.5/5,2010-02-09,Whether audiences will get behind The Lightnin...
4,m/0814255,Ethan Alter,True,Hollywood Reporter,Rotten,NaN,2010-02-10,What's really lacking in The Lightning Thief i...

In [16]:
rotten_tomatoes_movies.columns

Index(['rotten_tomatoes_link', 'movie_title', 'movie_info',
       'critics_consensus', 'content_rating', 'genres', 'directors', 'authors',
       'actors', 'original_release_date', 'streaming_release_date', 'runtime',
       'production_company', 'tomatometer_status', 'tomatometer_rating',
       'tomatometer_count', 'audience_status', 'audience_rating',
       'audience_count', 'tomatometer_top_critics_count',
       'tomatometer_fresh_critics_count', 'tomatometer_rotten_critics_count'],
      dtype='object')